import { VirtualDOMNode } from '../types/dom';

/**
 * PyMacs Reactive DOM Transpiler Engine
 *
 * Clarification of Principles:
 * DOM is NOT physics; DOM is the standard W3C Document Object Model (tree hierarchy of
 * elements, attributes, text nodes, and event listeners).
 * The Antigravity engine provides reactive layout and state reconciliation.
 *
 * Supported Targets:
 * 1. Reactive TypeScript (Signals, Effects, and Reactive DOM Observers)
 * 2. Reactive Kotlin (Kotlin Multiplatform, StateFlow, Coroutines, and Type-Safe DOM DSL)
 * 3. Reactive Python (AsyncIO, Reactive State Signals, and PyScript/FastHTML DOM bindings)
 */

export type ReactiveTargetLanguage = 'typescript' | 'kotlin' | 'python';

/**
 * Escapes string literals for code generation
 */
function escapeStr(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

/**
 * Converts VirtualDOMNode tree into Reactive TypeScript (using modern Reactive Signals)
 */
export function domToReactiveTypeScript(node: VirtualDOMNode): string {
  const nodeVar = `dom_${node.id.replace(/[^a-zA-Z0-9_$]/g, '_') || 'root'}`;
  
  function generateNodeTS(curr: VirtualDOMNode, depth: number): string {
    const pad = '  '.repeat(depth);
    const varName = `node_${curr.id.replace(/[^a-zA-Z0-9_$]/g, '_')}`;
    const tag = curr.tagName ? curr.tagName.toLowerCase() : 'div';
    const text = curr.textContent ? escapeStr(curr.textContent) : '';

    let out = `${pad}// <${tag} id="${curr.id}"> (Document Object Model Node)\n`;
    out += `${pad}const ${varName} = createReactiveElement("${tag}", {\n`;
    out += `${pad}  id: "${curr.id}",\n`;
    
    // Attributes
    if (curr.attributes && Object.keys(curr.attributes).length > 0) {
      out += `${pad}  attributes: {\n`;
      for (const [k, v] of Object.entries(curr.attributes)) {
        out += `${pad}    "${k}": "${escapeStr(v)}",\n`;
      }
      out += `${pad}  },\n`;
    }

    // Reactive styles
    if (curr.styles && Object.keys(curr.styles).length > 0) {
      out += `${pad}  styles: {\n`;
      for (const [k, v] of Object.entries(curr.styles)) {
        out += `${pad}    "${k}": "${escapeStr(v)}",\n`;
      }
      out += `${pad}  },\n`;
    }

    // Text content
    if (text) {
      out += `${pad}  textContent: "${text}",\n`;
    }

    out += `${pad}});\n\n`;

    // Children
    if (curr.children && curr.children.length > 0) {
      for (const child of curr.children) {
        out += generateNodeTS(child, depth);
        const childVar = `node_${child.id.replace(/[^a-zA-Z0-9_$]/g, '_')}`;
        out += `${pad}${varName}.appendChild(${childVar});\n`;
      }
    }

    return out;
  }

  return `/**
 * Generated by PyMacs Reactive DOM Transpiler
 * Target: TypeScript (Reactive Document Object Model with Signals)
 * 
 * Note: DOM represents the W3C Document Object Model tree structure,
 * reactively synchronized with application state via fine-grained signals.
 */

import { signal, computed, effect, Signal } from "pymacs/reactive";

export interface ReactiveElementProps {
  id: string;
  attributes?: Record<string, string>;
  styles?: Record<string, string>;
  textContent?: string;
}

export class ReactiveDOMElement {
  public readonly id: string;
  public readonly tagName: string;
  public readonly attributes: Map<string, Signal<string>>;
  public readonly styles: Map<string, Signal<string>>;
  public readonly textContent: Signal<string>;
  public readonly children: ReactiveDOMElement[] = [];

  constructor(tagName: string, props: ReactiveElementProps) {
    this.tagName = tagName;
    this.id = props.id;
    this.attributes = new Map();
    this.styles = new Map();
    this.textContent = signal(props.textContent || "");

    if (props.attributes) {
      for (const [key, val] of Object.entries(props.attributes)) {
        this.attributes.set(key, signal(val));
      }
    }

    if (props.styles) {
      for (const [key, val] of Object.entries(props.styles)) {
        this.styles.set(key, signal(val));
      }
    }
  }

  public appendChild(child: ReactiveDOMElement): void {
    this.children.push(child);
  }

  public setAttribute(name: string, value: string): void {
    const existing = this.attributes.get(name);
    if (existing) {
      existing.set(value);
    } else {
      this.attributes.set(name, signal(value));
    }
  }

  public mount(target: HTMLElement): void {
    const el = document.createElement(this.tagName);
    el.id = this.id;

    // Reactively bind attributes
    this.attributes.forEach((sig, name) => {
      effect(() => {
        el.setAttribute(name, sig.get());
      });
    });

    // Reactively bind text content
    effect(() => {
      el.textContent = this.textContent.get();
    });

    for (const child of this.children) {
      child.mount(el);
    }
    target.appendChild(el);
  }
}

export function createReactiveElement(tag: string, props: ReactiveElementProps): ReactiveDOMElement {
  return new ReactiveDOMElement(tag, props);
}

// -----------------------------------------------------------------------------
// Reactive DOM Tree Construction
// -----------------------------------------------------------------------------
export function buildReactiveDOMTree(): ReactiveDOMElement {
${generateNodeTS(node, 1)}
  return node_${node.id.replace(/[^a-zA-Z0-9_$]/g, '_')};
}
`;
}

/**
 * Converts VirtualDOMNode tree into Reactive Kotlin (Kotlin Multiplatform / StateFlow)
 */
export function domToReactiveKotlin(node: VirtualDOMNode): string {
  function generateNodeKT(curr: VirtualDOMNode, depth: number): string {
    const pad = '  '.repeat(depth);
    const tag = curr.tagName ? curr.tagName.toLowerCase() : 'div';
    const text = curr.textContent ? escapeStr(curr.textContent) : '';
    
    let out = `${pad}element("${tag}", id = "${curr.id}") {\n`;

    if (text) {
      out += `${pad}  text("${text}")\n`;
    }

    if (curr.attributes && Object.keys(curr.attributes).length > 0) {
      for (const [k, v] of Object.entries(curr.attributes)) {
        out += `${pad}  attr("${k}", "${escapeStr(v)}")\n`;
      }
    }

    if (curr.styles && Object.keys(curr.styles).length > 0) {
      for (const [k, v] of Object.entries(curr.styles)) {
        out += `${pad}  style("${k}", "${escapeStr(v)}")\n`;
      }
    }

    if (curr.children && curr.children.length > 0) {
      for (const child of curr.children) {
        out += generateNodeKT(child, depth + 1);
      }
    }

    out += `${pad}}\n`;
    return out;
  }

  return `/**
 * Generated by PyMacs Reactive DOM Transpiler
 * Target: Kotlin (Kotlin Multiplatform + Coroutines + StateFlow)
 * 
 * Note: DOM represents the standard W3C Document Object Model.
 * Reactivity is managed via Coroutines and MutableStateFlow.
 */

package org.pymacs.dom.reactive

import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

/**
 * Reactive DOM Node representation in Kotlin Multiplatform
 */
class ReactiveDOMNode(
    val tagName: String,
    val id: String,
    initialText: String = ""
) {
    val textContent: MutableStateFlow<String> = MutableStateFlow(initialText)
    val attributes: MutableMap<String, MutableStateFlow<String>> = mutableMapOf()
    val styles: MutableMap<String, MutableStateFlow<String>> = mutableMapOf()
    val children: MutableList<ReactiveDOMNode> = mutableListOf()

    fun text(value: String) {
        textContent.value = value
    }

    fun attr(name: String, value: String) {
        attributes.getOrPut(name) { MutableStateFlow(value) }.value = value
    }

    fun style(name: String, value: String) {
        styles.getOrPut(name) { MutableStateFlow(value) }.value = value
    }

    fun element(tag: String, id: String, init: ReactiveDOMNode.() -> Unit): ReactiveDOMNode {
        val child = ReactiveDOMNode(tag, id)
        child.init()
        children.add(child)
        return child
    }

    /**
     * Observes DOM reactive stream changes within a CoroutineScope
     */
    fun observeMutations(scope: CoroutineScope, onMutation: (String) -> Unit) {
        scope.launch {
            textContent.collect { newText ->
                onMutation("[\${id}] textContent changed to: $newText")
            }
        }
        children.forEach { it.observeMutations(scope, onMutation) }
    }
}

/**
 * DSL Entry point for constructing reactive DOM tree
 */
fun reactiveDOM(rootTag: String = "${node.tagName.toLowerCase()}", rootId: String = "${node.id}", init: ReactiveDOMNode.() -> Unit): ReactiveDOMNode {
    val root = ReactiveDOMNode(rootTag, rootId)
    root.init()
    return root
}

// -----------------------------------------------------------------------------
// Component Definition
// -----------------------------------------------------------------------------
fun createPyMacsDOM(): ReactiveDOMNode = reactiveDOM("${node.tagName.toLowerCase()}", "${node.id}") {
${generateNodeKT(node, 1)}
}
`;
}

/**
 * Converts VirtualDOMNode tree into Reactive Python (AsyncIO + Signal State)
 */
export function domToReactivePython(node: VirtualDOMNode): string {
  function generateNodePY(curr: VirtualDOMNode, depth: number): string {
    const pad = '  '.repeat(depth);
    const varName = `node_${curr.id.replace(/[^a-zA-Z0-9_$]/g, '_')}`;
    const tag = curr.tagName ? curr.tagName.toLowerCase() : 'div';
    const text = curr.textContent ? escapeStr(curr.textContent) : '';

    let out = `${pad}# <${tag} id="${curr.id}">\n`;
    out += `${pad}${varName} = ReactiveDOMNode(\n`;
    out += `${pad}    tag="${tag}",\n`;
    out += `${pad}    node_id="${curr.id}",\n`;
    out += `${pad}    text_content="${text}",\n`;
    
    // Attributes
    if (curr.attributes && Object.keys(curr.attributes).length > 0) {
      out += `${pad}    attributes={\n`;
      for (const [k, v] of Object.entries(curr.attributes)) {
        out += `${pad}        "${k}": "${escapeStr(v)}",\n`;
      }
      out += `${pad}    },\n`;
    }

    // Styles
    if (curr.styles && Object.keys(curr.styles).length > 0) {
      out += `${pad}    styles={\n`;
      for (const [k, v] of Object.entries(curr.styles)) {
        out += `${pad}        "${k}": "${escapeStr(v)}",\n`;
      }
      out += `${pad}    },\n`;
    }

    out += `${pad})\n`;

    if (curr.children && curr.children.length > 0) {
      for (const child of curr.children) {
        out += generateNodePY(child, depth);
        const childVar = `node_${child.id.replace(/[^a-zA-Z0-9_$]/g, '_')}`;
        out += `${pad}${varName}.append_child(${childVar})\n`;
      }
    }

    return out;
  }

  return `"""
Generated by PyMacs Reactive DOM Transpiler
Target: Python 3.12 (AsyncIO Reactive Document Object Model)

Note: DOM represents the W3C Document Object Model tree structure,
reactively bound through Python asyncio streams and state listeners.
"""

from typing import Dict, List, Optional, Callable, Any
import asyncio

class ReactiveSignal:
    """Reactive state signal for Document Object Model attributes and values."""
    def __init__(self, initial_value: Any):
        self._value = initial_value
        self._subscribers: List[Callable[[Any], None]] = []

    @property
    def value(self) -> Any:
        return self._value

    @value.setter
    def value(self, new_value: Any):
        if self._value != new_value:
            self._value = new_value
            self._notify()

    def subscribe(self, callback: Callable[[Any], None]):
        self._subscribers.append(callback)
        callback(self._value)

    def _notify(self):
        for sub in self._subscribers:
            sub(self._value)

class ReactiveDOMNode:
    """W3C Document Object Model representation with AsyncIO reactive bindings."""
    def __init__(
        self,
        tag: str,
        node_id: str,
        text_content: str = "",
        attributes: Optional[Dict[str, str]] = None,
        styles: Optional[Dict[str, str]] = None,
    ):
        self.tag: str = tag.lower()
        self.id: str = node_id
        self.text_content: ReactiveSignal = ReactiveSignal(text_content)
        self.attributes: Dict[str, ReactiveSignal] = {
            k: ReactiveSignal(v) for k, v in (attributes or {}).items()
        }
        self.styles: Dict[str, ReactiveSignal] = {
            k: ReactiveSignal(v) for k, v in (styles or {}).items()
        }
        self.children: List['ReactiveDOMNode'] = []
        self.parent: Optional['ReactiveDOMNode'] = None

    def append_child(self, child: 'ReactiveDOMNode') -> 'ReactiveDOMNode':
        child.parent = self
        self.children.append(child)
        return child

    def set_attribute(self, name: str, value: str):
        if name in self.attributes:
            self.attributes[name].value = value
        else:
            self.attributes[name] = ReactiveSignal(value)

    def render_to_html(self) -> str:
        attrs = " ".join(f'{k}="{v.value}"' for k, v in self.attributes.items())
        attr_str = f" {attrs}" if attrs else ""
        inner_children = "".join(c.render_to_html() for c in self.children)
        return f"<{self.tag} id=\\"{self.id}\\"{attr_str}>{self.text_content.value}{inner_children}</{self.tag}>"

    async def watch_mutations(self, queue: asyncio.Queue):
        """Streams all reactive DOM mutations into an asyncio queue."""
        self.text_content.subscribe(lambda val: queue.put_nowait(f"[{self.id}] textContent -> {val}"))
        for k, sig in self.attributes.items():
            sig.subscribe(lambda val, key=k: queue.put_nowait(f"[{self.id}] attr {key} -> {val}"))
        for child in self.children:
            await child.watch_mutations(queue)

def build_reactive_dom() -> ReactiveDOMNode:
    """Builds and returns the reactive Document Object Model tree."""
${generateNodePY(node, 1)}
    return node_${node.id.replace(/[^a-zA-Z0-9_$]/g, '_')}

if __name__ == "__main__":
    dom_tree = build_reactive_dom()
    print("Mounted Reactive DOM:")
    print(dom_tree.render_to_html())
`;
}

/**
 * Universal dispatcher for multi-target reactive DOM transpilation
 */
export function transpileDOMToTarget(node: VirtualDOMNode, target: ReactiveTargetLanguage): string {
  switch (target) {
    case 'typescript':
      return domToReactiveTypeScript(node);
    case 'kotlin':
      return domToReactiveKotlin(node);
    case 'python':
      return domToReactivePython(node);
    default:
      return domToReactiveTypeScript(node);
  }
}
