// Top-level / module build configuration for PyMacs Android Package
plugins {
    id 'com.android.application' version '8.2.2' apply false
}

apply plugin: 'com.android.application'

android {
    namespace 'org.pymacs.os'
    compileSdk 34

    defaultConfig {
        applicationId "org.pymacs.os"
        minSdk 26       // Android 8.0 Oreo
        targetSdk 34    // Android 14
        versionCode 40200
        versionName "4.2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86_64"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug // Sideload-friendly signature
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
